language: c
compiler:
  - gcc
#  - clang
script: 
  - cd "Build solutions/Traditional batch commands/"
  - bash buildSoftware.bash.sh
after_script:
  - cd ../../
  - './Build solutions/Traditional batch commands/Built software/Ｃ程式設計世界哈囉！(Hello C world!).exe'
