language: c
compiler:
  - gcc
  - clang
install:
  - sudo apt-get install mingw32
script: 
  - cd "Build solutions/Traditional batch commands/"
  - bash buildSoftware.bash.sh
  - bash buildSoftware.cross-compile.Windows_32bit.bash.sh
after_script:
  - cd ../..
  - pwd
  - bash -c 'LANGUAGE=zh_TW "./Build solutions/Traditional batch commands/Built software/Hello C world!.${CC}.exe"'
  - bash -c 'LANGUAGE=en "./Build solutions/Traditional batch commands/Built software/Hello C world!.${CC}.exe"'
  - bash -c 'LANGUAGE=zh_CN "./Build solutions/Traditional batch commands/Built software/Hello C world!.${CC}.exe"'
